ALTER TABLE tasks ADD COLUMN estimated_days INTEGER DEFAULT 0;
ALTER TABLE tasks ADD COLUMN estimated_minutes INTEGER DEFAULT 0;
ALTER TABLE tasks ADD COLUMN actual_days INTEGER DEFAULT 0;
ALTER TABLE tasks ADD COLUMN actual_minutes INTEGER DEFAULT 0;